version: '3.8'

services:
  sonarqube:
    image: sonarqube:community  
    container_name: sonarqube  # Nom explicite
    hostname: sonarqube  # pour la résolution DNS
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_WEB_JAVAOPTS=-Xmx1g -Xms512m  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/system/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - fastapi_network  

volumes:
  sonarqube_data:
  sonarqube_extensions:

networks:
  fastapi_network:
    external: true  # Utilise le réseau existant de votre application