name: FastAPI CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d --build

      - name: Wait for services to be ready
        run: |
          echo "Waiting for services to be ready..."
          sleep 30  # pour laisser le temps aux services (PostgreSQL, Redis, etc.)

      - name: Run tests inside FastAPI container
        run: |
          docker exec stage pytest

      - name: Shut down Docker Compose
        if: always()
        run: docker compose -f docker-compose.yml down
